In [1]:
import sys
import numpy as np
import math
from IPython.display import Image
import timeit

In [2]:
sys.version_info

sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)

In [3]:
np.__version__

'1.19.5'

In [4]:
if sys.platform == 'darwin' :
    print(" Mac OS")
else :
    print(" Windows ")

 Windows 


# 1. 텐서 구분 알아보기

           다차원 배열은 수학이나 물리학에서 tensor로 구성합니다.
           정수나 실수 등은 scalar로 물리량만 존재하지 방향이 없습니다. 그래서 0차원 텐서입니다.
           벡터는 물리량과 방향이 있는 1차원 텐서입니다.
           텐서는 기본으로 벡터가 기본 원소로 구성됩니다. 2차원인 행렬은 실제 벡터를 원소로 구성합니다.
           
           3차원일 경우는 내부는 2차원인 행렬을 원소로 구성합니다.
           

## 1-1 배열 알아보기

        배열은 하나의 자료형으로 원소를 구성합니다.
        파이썬 리스트는 object 자료형을 기준으로 원소를 구성합니다.
        

### 리스트도 하나의 배열입니다. 

In [6]:
l = [1,2,3,4]

In [7]:
l[0]

1

In [8]:
l[-1]

4

## 1-2 다차원 배열은 넘파이 모듈을 이용해서 만듭니다.

###  텐서 0차 : 스칼라 알아보기 

        scalar는 일반적인 숫자형입니다. 
        배열을 구성하면 텐서로 처리됩니다.
        

In [9]:
s = np.array(10)

In [10]:
s

array(10)

#### 차원이 0 차원 

In [11]:
s.ndim

0

In [12]:
s.shape

()

In [13]:
type(s)

numpy.ndarray

### 텐서 1차원 : 벡터 알아보기

        텐서 1차가 벡터이며 파이썬에서는 1차원 배열로 벡터를 표시합니다.
        

####  하나의 차원을 가진 정수값 리스트를 인자로 전달해서 다차원 배열에서 1차원 배열을 만듭니다.

In [14]:
#내부는 리스트, 밖에 어레이를 씌움
v = np.array([1,2,3,4, 5, 1])

In [15]:
v

array([1, 2, 3, 4, 5, 1])

#### 1차원 

In [16]:
v.ndim

1

In [17]:
v.shape

(6,)

#### 넘파이의 다차원 배열 클래스는 ndarray 입니다.

In [18]:
type(v)

numpy.ndarray

###  텐서 2차 : 행렬 알아보기

         행렬은 2차원 배열입니다. 텐서 2차이면 이 이름이 행렬입니다.
         

In [19]:
m = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

In [23]:
#6x3 행렬
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

#### 2차원 

In [24]:
m.ndim

2

In [25]:
m.shape

(6, 3)

#### 다차원 배열의 클래스는 벡터와 동일한 ndarray 클래스의 객체입니다.

In [26]:
type(m)

numpy.ndarray

###  텐서  3차원 이상 : 별도의 명칭이 없음  

         3차원 이상은 별도의 이름이 없어 텐서 3차라 부릅니다.
         

In [118]:
#2차원 [[1,2,3],[4,5,6] 와 2차원 [[7,8,9],[10,11,12]] 를 합쳐서 만든 3차원 텐서
c = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [119]:
# 2x2x3 텐서, (2,2,3) 텐서, 3차원 텐서
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### 3 차원

In [120]:
c.ndim

3

In [121]:
c.shape #이이삼차원이라 부른다

(2, 2, 3)

In [122]:
type(c)

numpy.ndarray

# 2. 다차원 배열 구조 알아보기

            넘파이의 다차원 배열은 ndarray 클래스에 의해 만들어진 객체입니다.
            이 클래스의 특징은 1차원 데이터를 관리합니다.  메타정보를 이용해서 이 1차원 데이터를 다양한 차원 데이터 뷰플 보여줍니다.
            
            데이터를 관리하는 영역과 메타정보를 관리하는 영역을 분리해서 처리해서 보다 신속한 계산을 처리합니다.
            

## 2-1 다차원 배열의 메타 정보 알아보기

        하나의 자료형만을 가져야 하므로 자료형을 있습니다.
        이 배열에 대한 크기, 하나의 원소에 대한 크기 등을 가집니다.
        
        또한 차원이나 모양 등을 구성합니다.

#### 모든 배열은 내부 원소에 대한 자료형을 가지고 있음 

In [123]:
c.dtype

dtype('int32')

#### 배열의 크기 및 원소 하나의 크기

In [124]:
# 2 x 2 x 3 =12, 2 x 2 x 3 텐서의 엘러먼트 수는 곱하면 나옴
c.size

12

#### 배열 원소 하나의 바이트 수

In [125]:
c.itemsize

4

#### 총 바이트 수

In [126]:
c.shape

(2, 2, 3)

In [127]:
# 총 엘러먼트 수(c.size) x 엘러먼트 하나 당 용량(c.itemsize) = 총 용량
c.size * c.itemsize

48

In [128]:
c.shape[0]

2

In [129]:
# 인덱스[0] x 인덱스[1] x 인덱스[2] = 총 엘러먼트 수
# 총 엘러먼트 수 x 엘러먼트 하나 당 용량(c.itemsize) = 총 용량
c.shape[0] * c.shape[1] * c.shape[2] * c.itemsize #각 차원의 개수를 곱에 원소 하나의 사이즈 곱하기

48

#### 배열을 확장할 때 메모리 상에서 확장되는 정보

### strides의 개념
     행렬 c의 구조에서 strides는 아래와 같다
![strides](strides.jpg)

In [130]:
c = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [131]:
#(2, 2, 3) 텐서에 대응됨
#(2, 2, 3) 텐서에서 index[0]로 총 용량(48바이트)를 나눈 값이 stride index[0] 값이 됨
#(2, 2, 3) 텐서에서 index[1]로 stride index[0]를 나눈 값이 stride index[1] 값이 됨
#(2, 2, 3) 텐서에서 index[2]로 stride index[1]를 나눈 값이 stride index[2] 값이 됨
c.strides

(24, 12, 4)

In [132]:
# index[0]와  stride index[0]를 곱하면 총 용량(48바이트)
# index[1]와  stride index[1]를 곱하면 stride index[0]
# index[2]와  stride index[2]를 곱하면 stride index[1]
c.shape[0] * c.strides[0]

48

In [133]:
c.shape[0] * c.strides[0]

48

## 2-2 실제 배열 내의  데이터는 1차원으로 구성됩니다.

#### 메모리에 있는 데이터 확인 : 

In [134]:
c.data

#### 내부 값 확인 

In [135]:
c.data.obj

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [136]:
c.flat

In [137]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### 특정 정보를 별도의 변수에 할당해서 새로운 사본이 생기지 않습니다

In [138]:
c[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [139]:
d_c = c[0]
d_c

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
d_c.base

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# 3. 다차원 배열 인덱스 및 슬라이스 검색

            파이썬 리스트는 단순히 인덱스 위치 정보를 가지고 검색이 가능합니다.
            넘파이 모듈은 검색 내에 배열을 넣어서 추가적인 검색도 가능합니다.
            
            이 배열이 정보가 논리값일 수도 있고 정수일 수도 있습니다. 
            이런 검색을 슬라이스에 연결해서 사용도 가능하도록 확장되었습니다.
            

### 3-1 다차원 배열 인덱스 검색도 원본을 유지

In [141]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [142]:
c.shape

(2, 2, 3)

In [143]:
c[0]

array([[1, 2, 3],
       [4, 5, 6]])

#### 배열의 첫번째 정보를 읽어오면 2차원 배열이 들어옴  

In [144]:
cc = c[0]

In [147]:
# 2 x 3 텐서, (2, 3) 텐서 
cc

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
# m X n matrix
cc.shape

(2, 3)

####  새로운 변수에 할당하면 원본도 변경이 됩니다

In [152]:
cc

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
cc[0] = np.array([1,2,3])

In [154]:
cc[0] = 999 #해당 배열 안의 모든 원소의 값이 바뀜

In [155]:
cc

array([[999, 999, 999],
       [  4,   5,   6]])

In [156]:
c # 원본도 바뀜

array([[[999, 999, 999],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

### 3-2 다차원 배열 슬라이스는 원본을 유지

         리스트에서 슬라이스 하면 새로운 사본을 만들지만 다차원 배열은 슬라이스를 해도 원본을 유지합니다.
         이런 이유는 다차원 배열은 대량의 원소를 메모리 상에 올라가 있으므로 다시 사본을 만들면 많은 메모리가 소비됩니다.
         
         그래서 슬라이스도 원본을 참조하는 방식으로 만들어져 있습니다.
         

#### 모든 데이터를 슬라이스로 처리

In [177]:
# : 은 ~ 같음. 시작값:마지막값 
#항상 그런 건 아니지만 넘파이에는 시작값은 포함되고 마지막값은 포함되지 않음, 시작값 이상 ~ 마지막값 미만
d = c[:] # : 왼쪽 인덱스 부터 오른쪽 인덱스 앞 까지 다 비워두면 처음 부터 끝까지

In [158]:
d.base

array([[[999, 999, 999],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [180]:
d[0]=3
d

array([[[ 3,  3,  3],
        [ 3,  3,  3]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [185]:
# (2, 2, 3) 텐서에서 index는 (2, 3)을 검색하는 것
# (2, 3) 텐서에서 index는 3을 검색하는 것
# (3) 텐서에서 index는 원소를 검색하는 것
d[0] = np.array([[3,3,3], [3,3,3]])
d

array([[[ 3,  3,  3],
        [ 3,  3,  3]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [186]:
c

array([[[ 3,  3,  3],
        [ 3,  3,  3]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [187]:
# : 은 ~와 유사한 개념
d = c[0:1] # : 왼쪽은 해당 인덱스 포함, 오른쪽은 해당 인덱스 미포함
d

array([[[3, 3, 3],
        [3, 3, 3]]])

####  새로운 객체가 만들어진다

In [188]:
d is c

False

In [189]:
d != c

array([[[False, False, False],
        [False, False, False]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

#### 데이터를 관리하는 메모리는 공유한다 

In [190]:
d.base is c

True

In [165]:
np.may_share_memory(d, c) # 메모리 공유하는지 확인

True

# 4. 추가된 검색 알아보기

    배열의 값으로 내부의 원소를 검색
    
    이 검색의 특징은 새로운 배열을 만든다.
    

### 4-1 논리 검색

        특정 원소를 검색해서 추출하기 위해 논리값이 True 일 경우만 추출합니다.
        이때 길이가 동일한 논리값을 가지는 배열을 만들어서 검색해야 합니다.
        

In [192]:
lll = np.array([1,2,3,4,5])
lll

array([1, 2, 3, 4, 5])

#### 배열의 원소가 3보다 큰 경우 처리하면 큰 경우만 True로 표시

In [193]:
con = lll > 3

In [194]:
con

array([False, False, False,  True,  True])

#### 검색연산자에 논리 배열을 넣으면 검색이 됩니다.

In [195]:
l4 = lll[con] #조건문 형태 con = lll > 3

#### 논리 검색은 새로운 사본을 만들어서 원본가 연결고리가 없습니다.


In [196]:
l4

array([4, 5])

In [204]:
con = lll > 3
l4 = lll[con] #조건문 형태 con = lll > 3
l4

array([4, 5])

In [197]:
l4.base

In [198]:
l4 is lll

False

In [205]:
#df[f].notnull()

#### 논리 검색된 결과를 변경해도 원본은 변경되지 않습니다.


In [215]:
#왼쪽 차원 index = 오른쪽 차원, 오른쪽 차원 = 왼쪽 차원 -1
l4[0] = 7777

In [207]:
l4

array([7777,    5])

In [208]:
lll

array([1, 2, 3, 4, 5])

## 4-2 팬시 검색

      배열 내의 원소를 검색할 때 정수형 배열을 만들어서 검색이 가능합니다. 
      이때도 논리 검색과 동일하게 새로운 사본을 만들어서 처리합니다.
      

In [216]:
lll

array([1, 2, 3, 4, 5])

#### 동일한 인덱스 정보를 넣고 추출하기

In [217]:
f = [0,1,0,1,1]

In [218]:
lll[[0,1,0,1,3]] #괄호 두개

array([1, 2, 1, 2, 4])

In [219]:
lll[f]

array([1, 2, 1, 2, 2])

#### 다른 인덱스 정보를 넣어서 추출합니다

In [220]:
f1 = [4,3,2,1,0]

In [221]:
l5 = lll[f1]

In [222]:
l5

array([5, 4, 3, 2, 1])

#### 새로운 사본이 만들어져서 갱신해도 원본에 영향이 없습니다.

In [223]:
l5.base

In [224]:
l5 is lll

False

In [225]:
l5[0] = 666

In [226]:
l5

array([666,   4,   3,   2,   1])

In [228]:
lll

array([1, 2, 3, 4, 5])

# 5. 다차원 배열 자료형 처리하기

           하나 자료형을 관리하기 위해서 다양한 자료형을 제공합니다.
           
           이런 이유는 배열의 데이터를 관리하는 기준이 c언어와 동일하므로 하나의 원소의 길이를 지정할 세부적인 자료형이 필요합니다.
           이 자료형으로 지정하면 한 바이트부터 여러바이트로 구성이 가능해서 실제 메모리 사용도 줄일 수 있습니다.
           
           

## 5-1 다차원 배열의 자료형은 하나의 객체를 보관

         다차원 배열을 만들기 위해 dtype 클래스를 제공합니다.
         

#### 넘파이에 자료형을 만드는 클래스가 별도로 존재 

In [229]:
np.dtype

numpy.dtype

#### 자료형을 관리하는 객체를 생성합니다.

In [230]:
dt = np.dtype(np.int8)

In [231]:
dt

dtype('int8')

In [232]:
isinstance(dt, np.dtype)

True

#### 자료형도 하나의 객체이므로 내부의 속성들을 확인합니다

In [233]:
dt.str

'|i1'

In [234]:
dt.char

'b'

In [235]:
dt.type

numpy.int8

In [236]:
dt.kind

'i'

In [237]:
dt.num

1

In [238]:
dt.descr

[('', '|i1')]

### 5-2 특정 자료형 객체로 다차원 배열을 생성

       자료형을 지정하지 않으면 원소들을 확인해서 특정 자료형으로 처리합니다.
       인자 dtype을 자료형을 지정하면 이 자료형으로 변경됩니다.
       

In [239]:
dt = np.dtype(np.int8) #int8 하여 4분의1로 감소

In [240]:
a = np.array([1,2,3,4], dtype = dt)

In [241]:
a

array([1, 2, 3, 4], dtype=int8)

In [242]:
a.dtype

dtype('int8')

In [243]:
a.itemsize #int8 하여 4분의1로 사이즈도 감소

1

In [244]:
a.strides

(1,)

In [245]:
b = np.array([1,2,3,4])

In [246]:
b

array([1, 2, 3, 4])

In [247]:
b.dtype

dtype('int32')

In [248]:
b.itemsize

4

In [249]:
b.strides

(4,)

# 6.  유니버셜 함수 알아보기

             다차원 배열의 원소가 많기 때문에 각 원소별로 계산을 하려면 순환문을 작성해야 하지만 유니버셜 함수는 기본으로 벡터화 연산을 지원하므로 
             실제 순환문없이 모든 원소의 계산을 수행합니다.
             
             

In [268]:
np.add

<ufunc 'add'>

## 6-1 유니버셜 함수란

     순환문 없이 모든 원소들을 자동으로 순환하면서 처리하는 함수 입니다.
    

### 파이썬 함수도 객체이므로 유니버셜 함수도 객체입니다.

       이 말은 해당되는 클래스가 존재합니다.

In [250]:
np.ufunc

numpy.ufunc

#### 넘파이 내의 함수의 클래스가 유니버셜 함수인지를 확인합니다.

In [251]:
type(np.add) == np.ufunc

True

#### 넘파이 모듈 내에 있는 유니버셜 함수를 확인합니다.

In [252]:
count = 0
for i,v in np.__dict__.items() :
    if type(v) == np.ufunc :
        print(i, end=", ")
        count += 1
    
    if count > 0  and count % 5  == 0 :
        print()

bitwise_not, matmul, absolute, add, arccos, 
arccosh, arcsin, arcsinh, arctan, arctan2, 
arctanh, bitwise_and, bitwise_or, bitwise_xor, cbrt, 
ceil, conj, conjugate, copysign, cos, 
cosh, deg2rad, degrees, divide, divmod, 

equal, exp, exp2, expm1, fabs, 
floor, floor_divide, float_power, fmax, fmin, 
fmod, frexp, gcd, greater, greater_equal, 
heaviside, hypot, invert, isfinite, isinf, 
isnan, isnat, lcm, ldexp, left_shift, 
less, less_equal, log, log10, log1p, 
log2, logaddexp, logaddexp2, logical_and, logical_not, 
logical_or, logical_xor, maximum, minimum, mod, 
modf, multiply, negative, nextafter, not_equal, 

positive, power, rad2deg, radians, reciprocal, 
remainder, right_shift, rint, sign, signbit, 
sin, sinh, spacing, sqrt, square, 
subtract, tan, tanh, true_divide, trunc, 

















































































































































































































In [269]:
#+-*///%=>< 유니버셜 함수 중 가장 빠르다

In [253]:
np.log(1)

0.0

### 6-2   파이썬은 연산자를 가지고 처리할 때 클래스 내부의 스페셜 메소드로 처리

#### 파이썬 연산자를 함수로 처리하는 모듈 

In [254]:
import operator as op

operator 연산자 관련 자료
https://docs.python.org/3.8/library/operator.html

In [255]:
op.add

<function _operator.add(a, b, /)>

#### 1차원 배열을 만드는 arrange 함수를 이용해서 원소 5개를 가진 배열을 만듭니다.

       0번부터 만들어지므로 4까지만 만들어집니다.

In [280]:
# arange에서 ,는 ~와 같음, np.arange(시작값, 마지막값, 간격) 에서 마지막값은 포함 안되는 정수를 불러낸다.
a = np.arange(0, 5, 2)
a

array([0, 2, 4])

In [281]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

#### 이 객체에도 __add__ 메소드가 있습니다. 

        이 메소드는 + 연산자를 처리하는 메소드입니다.

In [282]:
a.__add__

<method-wrapper '__add__' of numpy.ndarray object at 0x00000249EAA9ECB0>

#### 파이썬 연산자를 재구현한 add 함수를 호출할 경우에도 넘파이의 유니버셜 처리가 됩니다.

         이런 이유는 각 클래스에 정의된 스페셜 메소드를  호출하므로 넘파이의 스페셜 메소드가 처리됩니다.
         

In [283]:
(1).__add__

<method-wrapper '__add__' of int object at 0x00007FFE3BC42730>

In [284]:
op.add(1,1)

2

In [306]:
a = np.array([0,1,2,3,4])
#a + a
op.add(a,a)

array([0, 2, 4, 6, 8])

In [307]:
(1).__add__(1) #이렇게 쓸 수 있지만 굳이 쓸 일은 없을 듯

2

In [308]:
1+1

2

In [309]:
a

array([0, 1, 2, 3, 4])

In [310]:
op.add(a,a) #각 위치에 있는 것들끼리 더함

array([0, 2, 4, 6, 8])

In [311]:
a.__add__(a)

array([0, 2, 4, 6, 8])

### 6-3  파이썬 리스트의 덧셈 연산자는 리스트를 결합

        리스트의 덧셈연산은 두 개의 리스트를 연결합니다.
        다차원 배열의 덧셈은 두 개의 배열의 각각의 원소를 더합니다.

#### 리스트의 덧셈

In [332]:
l = [1,2,3,4]

In [325]:
l.__add__

<method-wrapper '__add__' of list object at 0x00000249EAAB1900>

In [326]:
l.__add__(l)

[1, 2, 3, 4, 1, 2, 3, 4]

In [327]:
op.add(l,l) #리스트는 두개를 연결함. 어레이랑 다름

[1, 2, 3, 4, 1, 2, 3, 4]

In [333]:
a = [1, 2, 3, 4]
for i in a:
    l.append(i)
l

[1, 2, 3, 4, 1, 2, 3, 4]

#### 다차원 배열의 덧셈 

In [337]:
l = [1, 2, 3, 4]
ll = np.array(l)#리스트를 어레이화
ll

array([1, 2, 3, 4])

In [338]:
op.add(ll,ll)

array([2, 4, 6, 8])

In [339]:
ll+ll

array([2, 4, 6, 8])

In [340]:
np.add(ll,ll)

array([2, 4, 6, 8])

In [341]:
#연산 속도 비교 test3가 제일 빠른듯 연산자 쓸 수 있으면 연산자 쓰기
#연산자로 표현할 수 없을 경우에 넘파이나 다른 함수 사용 

def test():
    #big_array = np.random.randint(1,100,size=10)
    
    return np.multiply(94283874,845758696)

def test2():
    #big_array = np.random.randint(1,100,size=10)
    return op.mul(94283874,845758696)

def test3():
    #big_array = np.random.randint(1,100,size=10)
    
    return 94283874*845758696

def test4():
    #big_array = np.random.randint(1,100,size=10)
    
    return (94283874).__mul__(845758696)

t1 = timeit.timeit('test()', setup='from __main__ import test', number=1000000)
t2 = timeit.timeit('test2()', setup='from __main__ import test2', number=1000000)
t3 = timeit.timeit('test3()', setup='from __main__ import test3', number=1000000)
t4 = timeit.timeit('test4()', setup='from __main__ import test4', number=1000000)

print(t1)
print(t2)
print(t3)
print(t4)

1.2237043000004633
0.16058720000000903
0.07201739999982237
0.1981627999994089


In [343]:
def test():
    #big_array = np.random.randint(1,100,size=10)
    
    return np.add(94283874,845758696)

def test2():
    #big_array = np.random.randint(1,100,size=10)
    return op.add(94283874,845758696)

def test3():
    #big_array = np.random.randint(1,100,size=10)
    
    return 94283874+845758696

def test4():
    #big_array = np.random.randint(1,100,size=10)
    
    return (94283874).__add__(845758696)

t1 = timeit.timeit('test()', setup='from __main__ import test', number=1000000)
t2 = timeit.timeit('test2()', setup='from __main__ import test2', number=1000000)
t3 = timeit.timeit('test3()', setup='from __main__ import test3', number=1000000)
t4 = timeit.timeit('test4()', setup='from __main__ import test4', number=1000000)

print(t1)
print(t2)
print(t3)
print(t4)

1.0200863999998546
0.12553850000040256
0.07034249999924214
0.15511960000003455


## 6-4 브로드캐스팅 처리

        다차원 배열을 처리하려면 두 배열의 원소의 개수를 일치시켜야 합니다.
        
        이를 자동으로 맞춰주는 과정이 브로드캐스팅입니다.
        

#### 스칼라의 브로드캐스팅

In [344]:
aa = np.arange(5)

In [345]:
aa

array([0, 1, 2, 3, 4])

In [346]:
aa + 5 # 모든 원소에 더하기 5

array([5, 6, 7, 8, 9])

In [347]:
aa + [5,5,5,5,5]

array([5, 6, 7, 8, 9])

In [358]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [359]:
a2 = np.arange(10).reshape(2,5) #0~9까지 2*5 텐서
#reshape()은 차원을 쪼개주는 것

In [360]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [365]:
# 텐서 값들의 곱 = 총 엘러먼트 수
# np.arange(총 엘러먼트 수).reshape(텐서값[0], 텐서값[1]...)
a2 = np.arange(2*5).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [366]:
n = 2
m = 5
a2 = np.arange(n*m).reshape(n, m) #방정식 같은 형태로 하면 효율적이고 좋다.
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 벡터의 브로드캐스팅

In [367]:
aa

array([0, 1, 2, 3, 4])

In [368]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [369]:
aa + a2

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [373]:
np.array([[0,1,2,3,4],[0,1,2,3,4]]) + a2

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [374]:
aa_b = np.array([aa,aa])

In [375]:
aa_b

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [376]:
a2 + aa_b

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

#### 행벡터와 열벡터를 계산할 때는 두 개의 벡터의 행과 열의 크기로 확대 

In [386]:
a_r = np.arange(1*5).reshape(1, 5)

In [387]:
a_r

array([[0, 1, 2, 3, 4]])

In [388]:
np.arange(5).reshape(1, 5)

array([[0, 1, 2, 3, 4]])

In [389]:
row = 1
column = 6
a_r = np.arange(row*column).reshape(row,column)

In [390]:
a_r

array([[0, 1, 2, 3, 4, 5]])

In [391]:
a_r.shape

(1, 6)

In [392]:
row = 6
column = 1
a_c = np.arange(row*column).reshape(row,column)

In [393]:
a_c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [394]:
a_c.shape

(6, 1)

In [405]:
# (1, x)텐서 + (y, 1)텐서 = (x , y)텐서
a_c + a_r #더하기는 잘 안씀

array([[ 0,  1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5,  6],
       [ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10]])

In [406]:
a_r + a_c

array([[ 0,  1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5,  6],
       [ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10]])

## 6-5 numpy 기초 사용법

        기본적으로 알아두어야될 사용법이 있습니다.
        
        자주 사용하니 여러번 활용해 보시기 바랍니다.
        

### 제로 행렬 만들기

In [410]:
r=5
c=4
num=np.zeros((r,c))
num

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [411]:
np.size(num)

20

In [412]:
num.shape

(5, 4)

### 1 행렬 만들기

In [413]:
one=np.ones((5,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 매트릭스 만들기

In [414]:
mat=np.matrix([[100,200],[300,400]])
mat

matrix([[100, 200],
        [300, 400]])

In [415]:
mat2=np.array([[100,200],[300,400]])
mat2

array([[100, 200],
       [300, 400]])

In [430]:
r=3
c=4
A = np.arange(r*c)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [431]:
A.reshape((r,c))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [434]:
r=3
c=4
A = np.arange(r*c).reshape((r,c))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [435]:
n=3
m=7
A = np.arange(n,m) #시작은 포함 끝은 미포함
A

array([3, 4, 5, 6])

In [419]:
x=2
y=2
A.reshape((x,y))

array([[3, 4],
       [5, 6]])

In [470]:
# 가우시안 정규 분포 난수 생성
# 정규 분포는 평균이0, 분산 1
R = np.random.randn(3, 4) #-도 나온다
R

array([[ 0.27337673,  1.1677887 ,  0.59068598,  0.51186776],
       [-0.54704352,  0.92103293,  0.43885914,  0.81118818],
       [ 0.75982543, -1.86344899, -2.03584289, -0.08346427]])

In [471]:
# 난수 생성 수가 무한히 늘어나면 R.mean()이 0에 도달
R.mean()

0.07873543002728386

In [472]:
# 0에서 1사이 균일 분포 난수 생성
RR = np.random.rand(3, 4) #이런 거 자주 쓴다
RR

array([[0.42963894, 0.3093126 , 0.56945771, 0.3342415 ],
       [0.18411162, 0.00193847, 0.34133836, 0.81839674],
       [0.84254327, 0.33738106, 0.54593   , 0.26151993]])

In [473]:
# 난수 생성 수가 무한히 늘어나면 R.mean()이 0.5에 도달
RR.mean()

0.4146508489037546

### 행렬에 값 치환/추출

In [489]:
a=np.array([0,0,0,0,0,0,0,0,0,0])
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [490]:
a=np.array([0,0,0,0,0,0,0,0,0,0])
a[0]=3
a[1]=5
a[7]=10
a

array([ 3,  5,  0,  0,  0,  0,  0, 10,  0,  0])

In [491]:
# 0이 아닌 값의 index 확인
np.nonzero(a)

(array([0, 1, 7], dtype=int64),)

In [492]:
a[a!=0]

array([ 3,  5, 10])

In [493]:
b = []
for i, number in enumerate(a):
    if number != 0:
        b.append(i)
np.array(b)        


array([0, 1, 7])

In [495]:
# ;; 간격
# 행렬을 거꾸로
a[::-1] # :이 한개면 범위 :: 두개는 간격 , -1은 제일 끝자리를 의미한다

array([ 0,  0, 10,  0,  0,  0,  0,  0,  5,  3])

In [501]:
n=4
m=3
r=np.random.rand(n,m)
r

array([[0.04402716, 0.72051322, 0.51576347],
       [0.23681113, 0.96419207, 0.86034865],
       [0.3544279 , 0.4891586 , 0.6306439 ],
       [0.73728662, 0.02915292, 0.77701414]])

In [531]:
# 최소, 최대값
r.min(), r.max() #실제로 사용

(0.029152917810033707, 0.9641920650713052)

In [532]:
# 평균, 총합
r.mean(), r.sum()

(0.5299449824346296, 6.359339789215555)

In [533]:
# 각 행에서 최대값을 나타내는 index 열
np.argmax(r,axis=1) #실제로 사용 axis=1 열

array([1, 1, 2, 2], dtype=int64)

In [534]:
# 각 열에서 최대값을 나타내는 index
np.argmax(r,axis=0)

array([3, 1, 1], dtype=int64)

In [541]:
#텐서 내에 가장 최대값을 나타내는 index
np.argmax(r) # 전체에서 가장 큰 값을 가진 인덱스

4

In [542]:
np.argmax(r, axis=0) #각 열에서 최댓값을 나타내는 행 axis=0은 god

array([3, 1, 1], dtype=int64)

In [543]:
# 평균, 총합
r.mean(), r.sum()

(0.5299449824346296, 6.359339789215555)

In [544]:
# n~m은 랜덤 정수의 범위, l은 난수 생성 개수
# np.random.randint는 list 형태로 도출됨
n=-5
m=10
l=11
r1=np.random.randint(n,m,l) #n은 포함 m은 미포함 시작 값은 포함 마지막 값은 미포함
r2=np.random.randint(n,m,l)
print(r1,r2)

[ 9  1 -5  2  9  3  2 -3 -4  7  3] [ 2 -5 -4  1 -2  7 -4 -5  9 -1  7]


In [545]:
# r1과 r2 간 공통값 추출
np.intersect1d(r1,r2)

array([-5, -4,  1,  2,  7,  9])

In [546]:
one=np.ones((5,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [547]:
# 각 행과 열의 위치의 값을 치환할 수 있음
# : 은 범위를 나타냄 시작 값은 포함되고 마지막 값은 포함되지 않음
# 첫행과 첫열은 0으로 시작한다

one[1:4,1:4]=0
print(one)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [548]:
z=np.zeros((10,10))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [549]:
#  :: 은 일정 간격을 나타낸다.
# 시작 값은 포함되고 시작 값이 없는 경우 0으로 간주한다.
# 마지막 값은 어떤 간격으로 입력되는지를 의미한다.
z=np.zeros((10,10))
z[0,1::2]=1
z[1,::2]=1
z[2,1::2]=1
z[3,::2]=1
z[4,1::2]=1

z[5,1::2]=1
z[6,::2]=1
z[7,1::2]=1
z[8,::2]=1
z[9,1::2]=1
#행은 고정, 열을 2칸 간격으로 1 삽입
#: 표현 방법이 많이 사용됨
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


# 7. 선형대수 계산하기

## 7-1 벡터의 내적 구하기

       내적은 두 벡터 간의 어떤 방향을 유지하는 지를 표시합니다.
       
       내젹이 양수이고 커지면 두 벡터가 유사한 방향을 가지는 것을 알 수 있습니다.
       내젹이 0이면 수직입니다. 내적이 음수이면 반대 방향을 알 수 있습니다.
       

       2차원 x 2차원 행렬의 내적은 아래와 같이 구할 수 있다.

![matrixdot](matrixdot.jpg)

## 2차원 텐서, 행렬의 내적

###    c11 = a11*b11 + a12*b21 + a13*b31 + .... + a1n*bn1
###    c21 = a21*b11 + a22*b21 + a23*b31 + .... + a2n*bn1
###    cmr = am1*b1r + am2*b2r + am3*b3r + .... + amn*bnr

### 1차원 행렬의 경우 내적에 사용되는 dot과 sumproduct에 사용되는 inner의 결과가 같다.

c11 = a11*b11 + a12*b21 + .... a1n*bn1  
c12 = a11*b12 + a12*b22 + .... a1n*bn2    
  .  
  .  
  .  
cmr = am1*b1r + am2*b2r + .... amn*bnr

In [608]:
w1 = np.random.rand(1)[0]
w2 = np.random.rand(1)[0]
w3 = np.random.rand(1)[0]
wd = np.random.rand(1)[0]

x1 = np.random.rand(1)[0]
x2 = np.random.rand(1)[0]
x3 = np.random.rand(1)[0]
xd = np.random.rand(1)[0]

w = np.array([w1, w2, w3, wd])
x = np.array([[x1], [x2], [x3], [xd]])
w, x

(array([0.01863936, 0.17314079, 0.46405783, 0.53676307]),
 array([[0.05196332],
        [0.83505748],
        [0.80190663],
        [0.10318431]]))

In [609]:
# 1차 함수 w*x+b
# 내적은 일차 함수 다발을 분류한 행렬들을 다시 합친 것
w1*x1 + w2*x2 + w3*x3 + wd*xd

0.5730676528414292

In [610]:
w = np.random.rand(4).reshape(1, 4)
w

array([[0.42543953, 0.37872959, 0.71020587, 0.74114449]])

In [611]:
x = np.random.rand(4).reshape(4, 1)
x

array([[0.59610778],
       [0.97862491],
       [0.09533162],
       [0.98737988]])

In [550]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [551]:
b = np.arange(3,8)
b

array([3, 4, 5, 6, 7])

In [552]:
c = np.array([[3],
              [4],
              [5],
              [6],
              [7]])
c

array([[3],
       [4],
       [5],
       [6],
       [7]])

#### dot 연산 처리

In [553]:
1*3 +2*4 + 3*5 + 4*6 + 5*7

85

In [554]:
a.dot(b) #편의성을 위해 둘다 1*4 행렬이지만 닷 연산을 허용

85

In [555]:
np.dot(a,b)

85

In [556]:
np.dot(a,c)

array([85])

#### inner 함수 처리 

In [557]:
# 1D array를 내적할때  dot과 동일한 결과가 나오나 2D 이상에서는 내적의 결과가 아닌 sumproduct 값이 도출됨.
np.inner(a,b)

85

In [558]:
np.inner(a,c)

ValueError: shapes (5,) and (1,5) not aligned: 5 (dim 0) != 1 (dim 0)

In [559]:
c = np.array([1,-2,3,8])

In [560]:
d = np.array([0,-3,3, 1])

In [612]:
np.dot(c,d)

array([  0, -18,  18,   6])

## 행렬곱 처리하기

        행렬 내의 벡터들이 내적을 가지고 다시 행렬을 구성합니다.
        
        dot, matmul 두 개를 지원합니다.
        

### 1차 텐서 닷 연산

In [613]:
r=1
c=6
A = np.arange(r*c).reshape((r,c))
A

array([[0, 1, 2, 3, 4, 5]])

In [614]:
B =np.arange(c*r).reshape((c,r))
B

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [615]:
np.dot(A,B)

array([[55]])

In [565]:
np.inner(A,B)

ValueError: shapes (1,6) and (1,6) not aligned: 6 (dim 1) != 1 (dim 0)

### 2차 텐서 닷 연산

In [566]:
r=10
c=6
A = np.arange(r*c).reshape((r,c))
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [567]:
B =np.arange(c*r).reshape((c,r))
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [568]:
np.dot(A,B)

array([[  550,   565,   580,   595,   610,   625,   640,   655,   670,
          685],
       [ 1450,  1501,  1552,  1603,  1654,  1705,  1756,  1807,  1858,
         1909],
       [ 2350,  2437,  2524,  2611,  2698,  2785,  2872,  2959,  3046,
         3133],
       [ 3250,  3373,  3496,  3619,  3742,  3865,  3988,  4111,  4234,
         4357],
       [ 4150,  4309,  4468,  4627,  4786,  4945,  5104,  5263,  5422,
         5581],
       [ 5050,  5245,  5440,  5635,  5830,  6025,  6220,  6415,  6610,
         6805],
       [ 5950,  6181,  6412,  6643,  6874,  7105,  7336,  7567,  7798,
         8029],
       [ 6850,  7117,  7384,  7651,  7918,  8185,  8452,  8719,  8986,
         9253],
       [ 7750,  8053,  8356,  8659,  8962,  9265,  9568,  9871, 10174,
        10477],
       [ 8650,  8989,  9328,  9667, 10006, 10345, 10684, 11023, 11362,
        11701]])

In [569]:
np.inner(A,B)

ValueError: shapes (10,6) and (10,6) not aligned: 6 (dim 1) != 10 (dim 0)

In [570]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [571]:
C = np.arange(r*c).reshape((r,c))
C

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [572]:
np.inner(A,C)

array([[   55,   145,   235,   325,   415,   505,   595,   685,   775,
          865],
       [  145,   451,   757,  1063,  1369,  1675,  1981,  2287,  2593,
         2899],
       [  235,   757,  1279,  1801,  2323,  2845,  3367,  3889,  4411,
         4933],
       [  325,  1063,  1801,  2539,  3277,  4015,  4753,  5491,  6229,
         6967],
       [  415,  1369,  2323,  3277,  4231,  5185,  6139,  7093,  8047,
         9001],
       [  505,  1675,  2845,  4015,  5185,  6355,  7525,  8695,  9865,
        11035],
       [  595,  1981,  3367,  4753,  6139,  7525,  8911, 10297, 11683,
        13069],
       [  685,  2287,  3889,  5491,  7093,  8695, 10297, 11899, 13501,
        15103],
       [  775,  2593,  4411,  6229,  8047,  9865, 11683, 13501, 15319,
        17137],
       [  865,  2899,  4933,  6967,  9001, 11035, 13069, 15103, 17137,
        19171]])

### 3차 텐서 닷 연산

In [616]:
np.arange(2*3*5)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [633]:
n=2
m=3
l=5
np.arange(n*m*l)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [634]:
#A = np.arange(n*m*l).reshape((n,m,g ....l))
#마지막 차원 값 .shape[-1]
A = np.arange(n*m*l).reshape((n,m,l))
A

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [635]:
#B = np.arange(n*m*l).reshape((n,g ....l, m))
# 마지막 차원값에서 두번째
B =np.arange(n*m*l).reshape((n,l,m)) #A의 마지막 차원 값l과 B 마지막에서 두번째 차원값 l이 같아야 내적구할수 있다.
B

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [636]:
s = 0
for i in range(l):
   s +=A[1][1][i] * B[0][i][2]
s

910

In [637]:
C[1][1][0][2]

910

In [638]:
A.dot(B)

array([[[[  90,  100,  110],
         [ 240,  250,  260]],

        [[ 240,  275,  310],
         [ 765,  800,  835]],

        [[ 390,  450,  510],
         [1290, 1350, 1410]]],


       [[[ 540,  625,  710],
         [1815, 1900, 1985]],

        [[ 690,  800,  910],
         [2340, 2450, 2560]],

        [[ 840,  975, 1110],
         [2865, 3000, 3135]]]])

In [639]:
# dot은 모든 경우의 내적이다.
C = np.dot(A,B)
C

array([[[[  90,  100,  110],
         [ 240,  250,  260]],

        [[ 240,  275,  310],
         [ 765,  800,  835]],

        [[ 390,  450,  510],
         [1290, 1350, 1410]]],


       [[[ 540,  625,  710],
         [1815, 1900, 1985]],

        [[ 690,  800,  910],
         [2340, 2450, 2560]],

        [[ 840,  975, 1110],
         [2865, 3000, 3135]]]])

In [640]:
C[0][0][0][0]

90

In [641]:
# (2,3,4) tensor와 (2,4,3) tensor의 내적은 4가 사라지고 앞 텐서는(2, 3), 뒤 텐서는 (2, 3) 만 남아 (2, 3, 2, 3) 텐서가 됨
np.dot(A,B).shape

(2, 3, 2, 3)

### matmul 함수 처리

In [642]:
np.matmul(A,B)

array([[[  90,  100,  110],
        [ 240,  275,  310],
        [ 390,  450,  510]],

       [[1815, 1900, 1985],
        [2340, 2450, 2560],
        [2865, 3000, 3135]]])

In [643]:
# matmul은 같은 차원끼리의 내적이다.
A1 = np.arange(m*l).reshape((m,l))
B1 =np.arange(m*l).reshape((l,m))
np.matmul(A1,B1)

array([[ 90, 100, 110],
       [240, 275, 310],
       [390, 450, 510]])

In [645]:
# n x m 행렬일 경우 즉 matrix가 1개일 경우 dot과 matmul의 결과는 동일하다.
np.dot(A1,B1)

array([[ 90, 100, 110],
       [240, 275, 310],
       [390, 450, 510]])

Dot과 matmul의 내적 방식의 차이는 아래 그림과 같습니다.
![dotmatmul](dotmatmul.jpg)

In [647]:
# n차 텐서와 n차 텐서 간 dot 곱 결과의 차원은 2 * (n-1) 이다.
x=100
A = np.arange(2*3*4*5*13*x).reshape((2,3,4,5,13,x))
B =np.arange(7*22*9*6*x*3).reshape((7,22,9,6,x,3))
np.dot(A,B).shape

(2, 3, 4, 5, 13, 7, 22, 9, 6, 3)

### 외적

두 벡터로 만들어지는 면의 시계 방향 수직 벡터로 외적의 크기는 두 벡터로 만들어지는 평행사변형 면적과 같다.
![cross](cross.jpg)

In [735]:
n=1
m=3

A = np.arange(n*m).reshape((n,m))
A

array([[0, 1, 2]])

In [736]:
B =np.arange(n*m).reshape((n,m))
B

array([[0, 1, 2]])

In [737]:
X=5
Y=0
np.cross(A+X,B+Y)

array([[  5, -10,   5]])

In [738]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

In [739]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.cross(x, y)

array([-3,  6, -3])

In [740]:
x = [4, 5, 6]
y = [1, 2, 3]
np.cross(x, y)

array([ 3, -6,  3])

In [741]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [742]:
y = np.array([[4,5,6], [1,2,3]])
y

array([[4, 5, 6],
       [1, 2, 3]])

In [743]:
np.cross(x, y)

array([[-3,  6, -3],
       [ 3, -6,  3]])

In [744]:
x = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [745]:
y = np.array([[7, 8, 9], [4,5,6], [1,2,3]])
y

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [746]:
np.cross(x, y)

array([[ -6,  12,  -6],
       [  0,   0,   0],
       [  6, -12,   6]])

### 전치행렬
 행렬의 행과 열을 바꿔 행렬의 축을 바꾸는 것

In [747]:
A = np.arange(2*3).reshape(2,3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [748]:
np.transpose(A)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [749]:
A.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [750]:
A.shape, A.T.shape

((2, 3), (3, 2))

In [751]:
A = np.arange(2*3*4).reshape(2,3,4)
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [752]:
np.transpose(A)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [753]:
A.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [754]:
A.shape, A.T.shape

((2, 3, 4), (4, 3, 2))

## 행렬식과 역행렬 구하기

      행렬식이 0 이면 역행렬이 없습니다. 

#### 행렬식, 역행렬 등을 구하는 모듈은 linalg 에 정의되어 있습니다.

In [5]:
import numpy.linalg as LA 

In [761]:
dir(LA)

['LinAlgError',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'cholesky',
 'cond',
 'det',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'lapack_lite',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

#### 행렬식 구하기
 연립 방정식의 해답이 유일한지 아닌지를 판단하는 공식을 행렬식이라고 한다. 행렬식의 값이 0이라는 뜻은 연립 방정식의 해답이 무한함을 의미한다.

연립방정식의 해답이 무한한 경우의 예로 아래의 그림과 같은 연립방정식에서 ad - bc = 0 일 경우이다.
해의 유일성 유무를 기하학적으로 표현하면 각 차원 공간의 방향성이 있는 부피를 의미한다. 
예를 들어 1차원에선 길이, 2차원에선 넓이, 3차원에선 부피로 각 차원에 해당하는 값이 행렬식의 값이 된다.  
행렬식의 값이 0인 경우 역행렬은 존재하지 않는다.

![det](det.jpg)

In [762]:
A = np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [763]:
# 행렬식 값 구하기
LA.det(A)

-2.0000000000000004

#### 랭크는 이 행렬에 수직인 경우가 없다는 것을 알 수 있습니다

In [764]:
LA.matrix_rank(A)

2

#### 역행렬 구하기

행렬과 역행렬을 곱하면 단위행렬(I로 표기)이 나온다.
해렬과 역행렬은 곱하는 순서가 바뀌어도 단위행렬이 나온다.
어떤 실수 A의 역수는 1/A로 둘의 곱이 1이 나오는 것처럼 역행렬은 행렬의 역 값이다.
2X2 행렬의 역행렬 공식에서 알 수 있듯이 행렬식 값이 0이면 역행렬은 존재하지 않는다.

![inversematrix1](inversematrix1.jpg)

In [772]:
# 행렬식이 0이 아닐 때 역행렬이 존재함
# 역행렬을 구하는 이유는 연립 방정식의 해를 구하기 위해서
# m x m 행렬에서만 역행렬이 존재함
LA.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [773]:
# 역행렬이 존재할 경우 무어-펜로즈 유사역행렬값과 같음.
# 모든 행렬에는 유사역행렬이 반드시 하나가 존재하고 해를 구하기 위해선 일반적으로 유사역행렬을 사용한다.
# 유사역행렬은 등가성 조건을 만족하지 않음. 왼쪽 유사역행렬 또는 오른쪽 유사역행렬 둘 중 하나만 만족한다.
LA.pinv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### 정방행렬도 행렬식이 0이면 역행렬이 존재하지 않음

In [767]:
D = np.array([[1,0,1],[-2,-3,1],[3,3,0]])
D

array([[ 1,  0,  1],
       [-2, -3,  1],
       [ 3,  3,  0]])

In [768]:
D.shape

(3, 3)

In [769]:
LA.det(D)

0.0

In [770]:
try :
    LA.inv(D)
except Exception as e :
    print("역행렬 없음")

역행렬 없음


#### 역행렬이 없는 경우 무어-펜로즈 유사역행렬(의사 역행렬)을 사용한다. 정방행렬이 아니라도 의사 역행렬을 구할 수 있다.

![pinverse](pinverse.jpg)

In [774]:
LA.pinv(D)

array([[ 0.25925926,  0.07407407,  0.18518519],
       [-0.14814815, -0.18518519,  0.03703704],
       [ 0.40740741,  0.25925926,  0.14814815]])

#### 정방행렬이 아니면 역행렬을 구할 수 없지만 의사 역행렬로 처리

In [818]:
# B는 C의 의사 역행렬
C = np.random.randn(5, 4)
C_ = np.linalg.pinv(C)

In [819]:
C

array([[ 1.22137103,  0.32590997, -0.59378159,  0.64600366],
       [ 2.69059332,  1.05246082,  0.23600181,  0.64502704],
       [ 0.40325813, -0.8559462 , -0.08039358,  0.38364673],
       [-1.87869064, -0.79310128,  1.18856664,  0.29141532],
       [-0.19361898, -1.6364612 , -0.6656578 , -0.94259396]])

In [820]:
C_

array([[-0.13807646,  0.41994531,  0.0761903 , -0.02648321,  0.21556549],
       [-0.06160497, -0.10089445, -0.41754683, -0.23762082, -0.35467393],
       [-0.63550506,  0.62077573, -0.07859883,  0.44912164,  0.09612334],
       [ 0.78462241, -0.29665999,  0.53484828,  0.24464535, -0.43284658]])

In [823]:
np.dot(C,C_)

array([[ 0.69549989, -0.0802221 ,  0.34915843, -0.21842719, -0.18900307],
       [-0.0802221 ,  0.97886508,  0.09198756, -0.05754575, -0.04979382],
       [ 0.34915843,  0.09198756,  0.59963361,  0.25046196,  0.21672247],
       [-0.21842719, -0.05754575,  0.25046196,  0.84331553, -0.13557765],
       [-0.18900307, -0.04979382,  0.21672247, -0.13557765,  0.88268589]])

In [825]:
# identity 행렬이 됨 np.dot(C_,C) = I
np.dot(C_,C)

array([[ 1.00000000e+00,  3.33066907e-16,  2.22044605e-16,
         1.94289029e-16],
       [ 1.38777878e-17,  1.00000000e+00,  2.77555756e-16,
        -3.88578059e-16],
       [-5.75928194e-16,  8.32667268e-17,  1.00000000e+00,
         1.80411242e-16],
       [ 8.60422844e-16, -9.99200722e-16,  0.00000000e+00,
         1.00000000e+00]])

In [822]:
C.shape

(5, 4)

#### 행렬과 역행렬로 처리한 것이 원래 행렬과 동일한 지 확인 

B는 C의 의사역행렬이다. C는 B의 의사역행렬인가? 아래의 식이 맞는지 확인해 보자.
![pinverse2](pinverse2.jpg)

In [826]:
# B와 C의 내적은 단위행렬이 나옴.
I = np.dot(C_, C)
I

array([[ 1.00000000e+00,  3.33066907e-16,  2.22044605e-16,
         1.94289029e-16],
       [ 1.38777878e-17,  1.00000000e+00,  2.77555756e-16,
        -3.88578059e-16],
       [-5.75928194e-16,  8.32667268e-17,  1.00000000e+00,
         1.80411242e-16],
       [ 8.60422844e-16, -9.99200722e-16,  0.00000000e+00,
         1.00000000e+00]])

In [827]:
# C와 단위행렬의 내적은 C가 도출됨.
np.dot(C, I)

array([[ 1.22137103,  0.32590997, -0.59378159,  0.64600366],
       [ 2.69059332,  1.05246082,  0.23600181,  0.64502704],
       [ 0.40325813, -0.8559462 , -0.08039358,  0.38364673],
       [-1.87869064, -0.79310128,  1.18856664,  0.29141532],
       [-0.19361898, -1.6364612 , -0.6656578 , -0.94259396]])

In [828]:
C

array([[ 1.22137103,  0.32590997, -0.59378159,  0.64600366],
       [ 2.69059332,  1.05246082,  0.23600181,  0.64502704],
       [ 0.40325813, -0.8559462 , -0.08039358,  0.38364673],
       [-1.87869064, -0.79310128,  1.18856664,  0.29141532],
       [-0.19361898, -1.6364612 , -0.6656578 , -0.94259396]])

In [829]:
# C와 np.dot(C, np.dot(B, C))은 허용오차 범위 내에 같은 값
np.allclose(C, np.dot(C, np.dot(C_, C)))

True

In [830]:
C - np.dot(C, np.dot(C_, C))

array([[-1.11022302e-15,  6.10622664e-16, -3.33066907e-16,
         1.11022302e-16],
       [-4.44089210e-16,  6.66133815e-16, -8.88178420e-16,
         0.00000000e+00],
       [-3.88578059e-16, -4.44089210e-16,  1.52655666e-16,
        -2.77555756e-16],
       [ 4.44089210e-16,  2.22044605e-16,  6.66133815e-16,
        -1.11022302e-16],
       [ 4.44089210e-16, -2.22044605e-15,  4.44089210e-16,
        -6.66133815e-16]])

In [831]:
# C의 의사역행렬인 B의 의사역행렬은 C임을 알수 있다.
C - np.linalg.pinv(C_)

array([[ 2.66453526e-15, -3.33066907e-16,  2.22044605e-16,
        -2.22044605e-16],
       [ 1.33226763e-15, -1.33226763e-15,  6.66133815e-16,
        -5.55111512e-16],
       [-1.44328993e-15, -2.22044605e-16,  3.33066907e-16,
         2.77555756e-16],
       [-4.44089210e-16,  3.33066907e-16, -1.99840144e-15,
         4.44089210e-16],
       [-4.71844785e-16,  3.33066907e-15,  1.11022302e-16,
         1.66533454e-15]])

In [832]:
E = np.dot(C, C_)
E

array([[ 0.69549989, -0.0802221 ,  0.34915843, -0.21842719, -0.18900307],
       [-0.0802221 ,  0.97886508,  0.09198756, -0.05754575, -0.04979382],
       [ 0.34915843,  0.09198756,  0.59963361,  0.25046196,  0.21672247],
       [-0.21842719, -0.05754575,  0.25046196,  0.84331553, -0.13557765],
       [-0.18900307, -0.04979382,  0.21672247, -0.13557765,  0.88268589]])

In [833]:
np.dot(C_, E)

array([[-0.13807646,  0.41994531,  0.0761903 , -0.02648321,  0.21556549],
       [-0.06160497, -0.10089445, -0.41754683, -0.23762082, -0.35467393],
       [-0.63550506,  0.62077573, -0.07859883,  0.44912164,  0.09612334],
       [ 0.78462241, -0.29665999,  0.53484828,  0.24464535, -0.43284658]])

In [834]:
C_

array([[-0.13807646,  0.41994531,  0.0761903 , -0.02648321,  0.21556549],
       [-0.06160497, -0.10089445, -0.41754683, -0.23762082, -0.35467393],
       [-0.63550506,  0.62077573, -0.07859883,  0.44912164,  0.09612334],
       [ 0.78462241, -0.29665999,  0.53484828,  0.24464535, -0.43284658]])

In [835]:
# B와 np.dot(B, np.dot(C, B))은 허용오차 범위 내에 같은 값
np.allclose(C_, np.dot(C_, np.dot(C, C_)))

True

In [836]:
# B 대신 C로 바꾸면 아래와 같이 내적을 할 수 없음. 
np.dot(C, np.dot(C, C_))

ValueError: shapes (5,4) and (5,5) not aligned: 4 (dim 1) != 5 (dim 0)

In [837]:
# 반대의 경우도 내적을 할 수 없음.
np.dot(C_, np.dot(C_, C))

ValueError: shapes (4,5) and (4,4) not aligned: 5 (dim 1) != 4 (dim 0)

## 문제 풀이

1. 아래와 같은 결과가 나오도록 코드를 작성하세요.
```
array([[[ 11,   9,  31],
        [ 13,   9,   6]],

       [[  2,   5, 192],
        [  1, 199, 212]]])
```

In [7]:
#  code 작성해보세요.
a = np.array([[[11, 9, 31], [13, 9, 6]], [[2, 5, 192], [1, 199, 212]]])
a

array([[[ 11,   9,  31],
        [ 13,   9,   6]],

       [[  2,   5, 192],
        [  1, 199, 212]]])

2. 위 array 값을 활용하여 3 보다 큰 값만 도출하는 논리검색을 통해 array를 도출해보세요.
```
array([ 11,   9,  31,  13,   9,   6,   5, 192, 199, 212])
```

In [8]:
#  code 작성해보세요.
a1 = a[a>3]
a1

array([ 11,   9,  31,  13,   9,   6,   5, 192, 199, 212])

3. 위 array를 활용하여 특정 index의 원소 값을 치환하여 아래 array를 도출해보세요.
```
array([  1,   2,   3,  13,   9,   6,   5, 192, 199, 212])
```

In [9]:
#  code 작성해보세요.
a1[0] = 1
a1[1] = 2
a1[2] = 3
a1

array([  1,   2,   3,  13,   9,   6,   5, 192, 199, 212])

4. 위 array를 활용하여 팬시검색을 통해 아래 array를 도출해보세요.
```
array([  2,   1,   6,   5, 212])
```

In [11]:
#  code 작성해보세요.
# index에서 -1은 마지막 index 값 도출
a1[[1, 0, 5, 6, 9]]

array([  2,   1,   6,   5, 212])

5. arange와 reshape을 활용하여 아래 array를 도출해보세요.
```
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])
```

In [12]:
#  code 작성해보세요.
a2 = np.arange(18).reshape(3, 6)
a2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

6. 위 array를 활용하여 아래 array를 도출해보세요.
```
array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34]])
```

In [14]:
#  code 작성해보세요.
# a2 + a2
a2 * 2

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34]])

7. 아래 array를 도출해보세요.
```
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])
```

In [929]:
#  code 작성해보세요.
z=np.zeros((6,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

8. 위 array를 활용하여 아래 array를 도출해보세요.
```
array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 1.]])
```

In [922]:
#  code 작성해보세요.
z=np.zeros((6,5))

z[0,1::3]=1
z[1,::2]=1
z[2,1::3]=1
z[3,::2]=1
z[4,1::3]=1

z[5,0::2]=1
z

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 1.]])

9. 아래 array를 도출해보세요.
```
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])
```

In [921]:
#  code 작성해보세요.
o=np.ones((7,7))
o

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

10. 위 array를 활용하여 아래 array를 도출해보세요.
```
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])
```

In [920]:
#  code 작성해보세요.
o[1:6,1:6]=0
o

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

11. 아래 두 array의 내적을 해 내적값을 도출해보세요.
```
array([2, 3, 4, 5, 6, 7])
array([ 5,  6,  7,  8,  9, 10])
내적값:220
```

In [23]:
#  code 작성해보세요.
d = np.array([2, 3, 4, 5, 6, 7])
e = np.array([ 5,  6,  7,  8,  9, 10])
#np.dot(d, e) 교차 내적값까지 필요한 경우
#np.inner(d, e) sumproduct을 할 경우
#np.matmul(d, e) 같은 차원 내적만 필요한 경우
# d, e 모두 1차원 텐서이기 때문에 모두 동일하게 나온다.
d.dot(e)

220

12. arange와 reshape을 활용하여 아래 두 array를 도출하고 두 array의 내적을 해 내적값을 도출해보세요.
```
array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])
```
```
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])
```
내적값

```
array([[ 546,  567,  588,  609,  630,  651],
       [1428, 1498, 1568, 1638, 1708, 1778],
       [2310, 2429, 2548, 2667, 2786, 2905],
       [3192, 3360, 3528, 3696, 3864, 4032],
       [4074, 4291, 4508, 4725, 4942, 5159],
       [4956, 5222, 5488, 5754, 6020, 6286]])
```

In [918]:
#  code 작성해보세요.
d1 = np.arange(42).reshape(6, 7)
e1 = np.arange(42).reshape(7, 6)
np.dot(d1,e1)

array([[ 546,  567,  588,  609,  630,  651],
       [1428, 1498, 1568, 1638, 1708, 1778],
       [2310, 2429, 2548, 2667, 2786, 2905],
       [3192, 3360, 3528, 3696, 3864, 4032],
       [4074, 4291, 4508, 4725, 4942, 5159],
       [4956, 5222, 5488, 5754, 6020, 6286]])

13. arange와 reshape을 활용하여 아래 두 array를 도출하고 두 array의 내적을 해 내적값을 도출해보세요.
```
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])
```
```
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])
```
내적값
```
array([[[[  90,  100,  110],
         [ 240,  250,  260]],

        [[ 240,  275,  310],
         [ 765,  800,  835]],

        [[ 390,  450,  510],
         [1290, 1350, 1410]]],

       [[[ 540,  625,  710],
         [1815, 1900, 1985]],

        [[ 690,  800,  910],
         [2340, 2450, 2560]],

        [[ 840,  975, 1110],
         [2865, 3000, 3135]]]])
```

In [24]:
#  code 작성해보세요.
d1 = np.arange(30).reshape(2, 3, 5)
e1 = np.arange(30).reshape(2, 5, 3)
np.dot(d1, e1)

array([[[[  90,  100,  110],
         [ 240,  250,  260]],

        [[ 240,  275,  310],
         [ 765,  800,  835]],

        [[ 390,  450,  510],
         [1290, 1350, 1410]]],


       [[[ 540,  625,  710],
         [1815, 1900, 1985]],

        [[ 690,  800,  910],
         [2340, 2450, 2560]],

        [[ 840,  975, 1110],
         [2865, 3000, 3135]]]])

14. 위 두 array를 활용하여 matmul을 해보세요.

matmul 결과
```
array([[[  90,  100,  110],
        [ 240,  275,  310],
        [ 390,  450,  510]],

       [[1815, 1900, 1985],
        [2340, 2450, 2560],
        [2865, 3000, 3135]]])
```

In [915]:
#  code 작성해보세요.
np.matmul(e1,d1)

array([[[  90,  100,  110],
        [ 240,  275,  310],
        [ 390,  450,  510]],

       [[1815, 1900, 1985],
        [2340, 2450, 2560],
        [2865, 3000, 3135]]])

15. 아래 두 array를 외적을 해보세요.
```
array([[12,  0,  4],
       [ 3,  9, 66],
       [ 1,  7,  8]])
```
```
array([[ 55,  21,   3],
       [  8,  43,   7],
       [109,  22,  76]])
```

외적값
```
array([[  -84,   184,   252],
       [-2775,   507,    57],
       [  356,   796,  -741]])
```

In [914]:
#  code 작성해보세요.
x = np.array([[12,  0,  4],
       [ 3,  9, 66],
       [ 1,  7,  8]])
y = np.array([[ 55,  21,   3],
       [  8,  43,   7],
       [109,  22,  76]])
np.cross(x, y)

array([[  -84,   184,   252],
       [-2775,   507,    57],
       [  356,   796,  -741]])

16. arange와 reshape을 활용해 아래 array를 만들고 전치행렬을 도출해보세요.
```
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])
```

전치행렬
```
array([[[ 0, 12],
        [ 3, 15],
        [ 6, 18],
        [ 9, 21]],

       [[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]]])
```

In [913]:
#  code 작성해보세요.
a4 = np.arange(24).reshape(2,4,3)
a4.T

array([[[ 0, 12],
        [ 3, 15],
        [ 6, 18],
        [ 9, 21]],

       [[ 1, 13],
        [ 4, 16],
        [ 7, 19],
        [10, 22]],

       [[ 2, 14],
        [ 5, 17],
        [ 8, 20],
        [11, 23]]])

17. 아래 행렬의 행렬식과 역행렬을 구하세요.
```
array([[0, 1],
       [2, 3]])
```
행렬식 : -2

역행렬
```
array([[-1.5,  0.5],
       [ 1. ,  0. ]])
```

In [912]:
#  code 작성해보세요.
a5 = np.array([[0, 1],
       [2, 3]])

LA.det(a5)

-2.0

In [911]:
#  code 작성해보세요.
LA.inv(a5)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

18. arange와 reshap을 활용하여 array를 만들고 의사역행렬을 도출하세요
```
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
```
의사역행렬
```
array([[-0.475,  0.175],
       [-0.2  ,  0.1  ],
       [ 0.075,  0.025],
       [ 0.35 , -0.05 ]])
```

In [910]:
#  code 작성해보세요.
a6 = np.array([[0, 1, 2, 3],
   [4, 5, 6, 7]])
LA.pinv(a6)

array([[-0.475,  0.175],
       [-0.2  ,  0.1  ],
       [ 0.075,  0.025],
       [ 0.35 , -0.05 ]])